# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b727bc9f010eb0f666562c47bd29447df7a5d1f953d16ece29f22e79792c23843022812827d4f66cb08784f733f8423d53ca77df3a907099f18c13f3bac658f

test:
  secret_key_base: f92089f7772428745bf4413b376b03f0d0e337599e8bc031e3385ca4ed502fd0493b96c6b42afc01a8f12f8414ffa55ff0e5efca19c9a8474fbca508175beab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
